config/routes.rb
Archives::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  
  resources :recordings

  resources :salutations

  match "services/search", :controller => :services, :action => :search
  match "archives/services/results", :controller => :services, :action => :results
  match "services/results", :controller => :services, :action => :results
  match "archives/services/problems", :controller => :services, :action => :problems
  match "services/problems", :controller => :services, :action => :problems
  match "services/statistics", :controller => :services, :action => :statistics
  resources :services
  match "services/:month/:day/:year", :controller => :services, :action => :show

  resources :kinds

  resources :speakers

  root :to => 'services#index'

end

app/models/service.rb
class Service < ActiveRecord::Base
	belongs_to :kind
	has_many :ministrations
	has_many :speakers, :through => :ministrations
	has_many :recordings, :dependent => :destroy

	cattr_reader :per_page
  @@per_page = 50

	scope :year, lambda { |y| { :conditions => "YEAR(date_of_service) = #{y}",
 		:order => "date_of_service", :include => [ :recordings, { :speakers => :salutation } ] } }

	scope :speaker, lambda { |s| { :conditions => "speakers.id = #{s}",
 		:order => "date_of_service", :include => [ :recordings, { :speakers => :salutation } ] } }

	def self.years
		#ys = []
		#Service.all.collect { |s| ys << s.date_of_service.year }
		#ys.uniq!
		ys = (1984..2011).to_a
	end

	def self.multiple(y)
		ms = []
		Service.find(:all, :conditions => "YEAR(date_of_service) = #{y}").collect do |s|
		 	ms << s if s.recordings.count > 1
		end
		ms.count
	end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /services
  # GET /services.xml
  def index
		@years = Service.years
		if !params[:speaker].nil?
			@services = Service.speaker(params[:speaker])
		elsif !params[:year].nil?
			@services = Service.year(params[:year])
			session[:year] = params[:year]
		elsif !session[:year].nil?
			@services = Service.year(session[:year])
		else
			y = @years.last
			@services = Service.year(y)
			session[:year] = y
		end
    #@services = Service.paginate :page => params[:page], :order => 'date_of_service DESC'
		#will_paginate @services, :class => "ui-widget ui-state-highlight ui-corner-all", :style => "margin-top: 20px; padding: 0.7em; text-align: center;" %>
		
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @services }
    end
  end

  # GET /services/1
  # GET /services/1.xml
  def show
		if params[:year]
			service_date = Date.new(params[:year].to_i, params[:month].to_i, params[:day].to_i)
			@service = Service.find_by_date_of_service(service_date)
		else
			@service = Service.find(params[:id])
		end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @service }
    end
  end

  # GET /services/new
  # GET /services/new.xml
  def new
    @service = Service.new
		@service.ministrations.build
		@speakers = Speaker.all(:include => :salutation, :order => "last_name, first_name")

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
		@speakers = Speaker.all(:include => :salutation, :order => "last_name, first_name")
  end

  # POST /services
  # POST /services.xml
  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        flash[:notice] = 'Service was successfully created.'
        format.html { redirect_to(@service) }
        format.xml  { render :xml => @service, :status => :created, :location => @service }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.xml
  def update
		params[:service][:existing_ministration_attributes] ||= {}
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
				@service.recordings.each { |r| r.rename }
        flash[:notice] = 'Service was successfully updated.'
        format.html { redirect_to(@service) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.xml
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to(services_url) }
      format.xml  { head :ok }
    end
  end

	def problems
		@services = Service.all(:order => 'date_of_service')
		#@no_speakers = @services.map { |s| s if !s.title.nil? && s.speakers.empty? &&
		#	s.kind_id < 3 && s.title != "N/A" && !s.title.match(/^No Service/) }.compact
		@no_speakers = []
		#@no_titles = @services.map { |s| s if s.title.nil? && !s.speakers.empty? }.compact
		@no_titles = []
		@neither = @services.map { |s| s if s.title.nil? && s.speakers.empty? }.compact
		@off_days = @services.select { |s| s.date_of_service.wday == 1 || ((s.date_of_service.wday == 2 || s.date_of_service.wday == 4)	&& s.date_of_service.year.to_i > 1991) }
	end

	def search
		@speakers = Speaker.all(:include => :salutation)
	end

	def results
		@services = Service.find(:all, :include => :speakers,
			:conditions => "title like '%#{params[:services][:title]}%'",
			:order => "date_of_service")
		unless params[:services][:speaker_id].empty?
			@services = @services.select { |s| s.speaker_ids.include?(
				params[:services][:speaker_id].to_i) }
		end
		unless params[:services][:kind_id].empty?
			@services = @services.select { |s| s.kind_id == 
				params[:services][:kind_id].to_i }.compact
		end
	end
	
	def statistics
		@years = Service.years
	end

end

app/helpers/services_helper.rb
module ServicesHelper

	def add_ministration_link(name)
		link_to_function name do |page|
			page.insert_html :bottom, :ministrations, :partial => 'ministration', :object => Ministration.new
		end
	end
  
end

app/views/services/index.html.haml
.container
  .row
    .col-md-9
      %h1 Services
      %table.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th Date
            %th Kind
            %th Title
            %th Speaker(s)
            %th Recording(s)
        %tbody
          - @services.each do |service|
            %tr
              %td= link_to preferred_date_format(service.date_of_service), service_path(service)
              %td= service.kind.designation unless service.kind.nil?
              %td= service.title
              %td= service.speakers.collect { |sp| link_to sp.full_name, speaker_path(sp) }.to_sentence.html_safe
              %td
                - service.recordings.each do |r|
                  %a{href: r.linky}
                    %img{src: r.ploty, width: 100, height: 50, border: 1}
    .col-md-3
      %h3 Jump to Year
      %ul.nav.nav-pills.nav-stacked#myPills
        - @years.reverse.each do |y|
          %li
            = link_to({ :controller => 'services', :action => 'index', :year => y }) do
              = y
              %span.badge
                = Service.year(y).count
:javascript
  $(document).ready(function() {
    $('#services').dataTable({
      "bJQueryUI": true,
      "sPaginationType": "full_numbers"
    });
  });

app/views/services/problems.html.haml
%h1 Services with Metadata Problems

- unless @no_speakers.count == 0
  %h2 No Speakers (#{@no_speakers.count})
  %table.table
    %tr
      %th Date of Service
      %th Title
    - @no_speakers.each do |service|
      %tr
        %td= link_to preferred_date_format(service.date_of_service), edit_service_path(service)
        %td= service.title

- unless @no_titles.count == 0
  %h2 No Titles (#{@no_titles.count})
  %table.table
    %tr
      %th Date of Service
      %th Speaker(s)
    - @no_titles.each do |service|
      %tr
        %td= link_to preferred_date_format(service.date_of_service), edit_service_path(service)
        %td= service.speakers.map { |sp| sp.proper_name }.to_sentence

- unless @neither.count == 0
  %h2 No Speakers or Title (#{@neither.count})
  %table.table
    %tr
      %th Date of Service
      %th Recording(s)?
    - @neither.each do |service|
      %tr
        %td= link_to preferred_date_format(service.date_of_service), edit_service_path(service)
        %td= service.recordings.count

- unless @off_days.count == 0
  %h2 Services on "Off" Days (#{@off_days.count})
  %table.table
    %tr
      %th Date of Service
      %th Speaker(s)
      %th Title
    - @off_days.each do |service|
      %tr
        %td= link_to preferred_date_format(service.date_of_service), edit_service_path(service)
        %td= service.speakers.collect { |sp| link_to sp.full_name, admin_speaker_path(sp) }.to_sentence.html_safe
        %td= service.title

app/views/services/results.html.erb
<h1>Search results (<%= @services.count %>)</h1>

<table>
  <tr><th>Date<th>Title<th>Speaker(s)<th>Recording(s)
  </tr>

<% @services.each do |service| %>
  <tr>
		<td><%= preferred_date_format(service.date_of_service) %></td>
		<td><%= link_to service.title, service %></td>
		<td><%= service.speakers.map { |sp| link_to sp.proper_name, sp }.join('<br/>') %></td>
		<td><%= service.recordings.map { |r| link_to r.id, r }.join('<br/>') %></td>
  </tr>
<% end %>
</table>

app/views/services/search.html.erb
<h1>Searching services</h1>

<% form_for :services, :url => { :action => :results } do |f| %>
  <table>
    <tr><th>Title<td><%= f.text_field :title %></tr>
    <tr><th>Speaker<td><%= f.collection_select :speaker_id, @speakers,
      :id, :proper_name, :include_blank => true %></tr>
    <tr><th>Kind<td><%= f.collection_select :kind_id, Kind.all, :id,
      :designation, :include_blank => true %></tr>
  </table>

  <p>
		<%= f.submit 'Search', :class => "fg-button ui-state-default ui-corner-all" %>
	</p>
<% end %>

app/views/services/show.html.haml
%h1 Service

%table
  %tr
    %th Date
    %td= preferred_date_format(@service.date_of_service)
  %tr
    %th Title
    %td= @service.title
  %tr
    %th Kind
    %td= @service.kind.designation unless @service.kind.nil?
  %tr
    %th Speaker(s)
    %td= @service.speakers.collect { |sp| link_to sp.full_name, speaker_path(sp) }.to_sentence.html_safe
  %tr
    %th Recording(s)
    %td= @service.recordings.map { |r| link_to r.filename, r }.join('<br/>').html_safe

app/views/services/statistics.html.haml
%h1 Service Statistics

%table.table.table-striped.table-bordered.table-hover
	%thead
		%th Year
		%th Services
		%th Recordings
		%th Multiple
		%th Missing
		%th Complete
	%tbody
		- count_s = count_r = count_m = count_x = 0
		- @years.each do |y|
			- services = Service.year(y); count_s += services.count
			- recordings = Recording.year(y); count_r += recordings.count
			- multiples = services.select { |s| s.recordings.count > 1 }; count_m += multiples.count
			- missings = services.select { |s| s.recordings.count == 0 }; count_x += missings.count
			%tr
				%td= link_to y, { :controller => 'services', :action => 'index', :year => y }
				%td= services.count
				%td= recordings.count - multiples.count
				%td= multiples.count
				%td= missings.count
				%td
					= ((services.count - missings.count) / services.count.to_f * 100).round
					\%
			= " | " unless y = @years.last
	%tfoot
		%th
		%th= count_s
		%th= count_r - count_m
		%th= count_m
		%th= count_x
		%th
			= (((count_s - count_x) / count_s.to_f) * 100).round
			\%